### ISSUE TITLE
Need to update package.json with bluebird

### ISSUE THREAD

**Issue by redrockzee** [yehya/express-longpoll#3]
I am able to use your module.  Nice work with this!  Better than socket.io by orders of magnitude! 

But initially I got this error.  After I added bluebird to my own package.json it worked fine.

Error: Cannot find module 'bluebird'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\devel\dov\node_modules\express-longpoll\index.js:2:15)

**Comment by yehya** [comment]
Oh whoops,. Thanks a ton, I would have never found out about that till you mentioned it!
